(*
 * merge.applescript — AppleScript 原生的单文件合并工具
 *
 * 用法:  osascript merge.applescript <stepName>
 *   e.g. osascript merge.applescript stepA_mal
 *
 * 作用: 把 types / reader / printer 三个模块与 <stepName>.applescript
 *       合并成一个零依赖的 <stepName>.standalone.applescript，
 *       再用 osacompile 即可得到无外部依赖的 .standalone.scpt。
 *
 * 合并策略(扁平化, 顶层唯一 use framework):
 *   - types / printer 模块整体内联到顶层(它们是 script 对象)
 *   - reader 模块平铺到顶层, 内部 typesLib 重命名为 readerTypesLib
 *   - core 模块平铺到顶层(零冲突, 通过 inject 注入依赖)
 *   - 去掉 reader 中与 step 重复定义的顶层 handler(避免重复定义报错)
 *   - step 的 loader 块改为 set ... to me (模块已在当前脚本内)
 *   - 删除 step 中仅用于外部加载的 loadMod / fileExists 助手
 *
 * 不使用 Python, 不依赖 shell 文本处理; 文件读写用 AppleScript 原生能力。
 *)

use AppleScript version "2.4"
use scripting additions

on run(argv)
	if (count of argv) < 1 then
		error "usage: osascript merge.applescript <stepName>"
	end if
	set stepName to item 1 of argv
	set baseDir to do shell script "dirname " & quoted form of (POSIX path of (path to me))

	set typesSrc to my readFile(baseDir & "/types.applescript")
	set readerSrc to my readFile(baseDir & "/reader.applescript")
	set printerSrc to my readFile(baseDir & "/printer.applescript")
	set coreSrc to my readFile(baseDir & "/core.applescript")
	set stepSrc to my readFile(baseDir & "/" & stepName & ".applescript")

	-- 去掉各文件顶部的 use 行(合并后由唯一 header 提供)
	set typesBody to my stripUse(typesSrc)
	set readerBody to my stripUse(readerSrc)
	set printerBody to my stripUse(printerSrc)
	set coreBody to my stripUse(coreSrc)
	set stepBody to my stripUse(stepSrc)

	-- reader 内部依赖 typesLib -> 重命名为 readerTypesLib (保留 setTypesLib 助手名)
	set readerBody to my replaceStr(readerBody, "property typesLib", "property readerTypesLib")
	set readerBody to my replaceStr(readerBody, "set typesLib", "set readerTypesLib")
	set readerBody to my replaceStr(readerBody, "my typesLib", "my readerTypesLib")

	-- 去重: 删除 reader 中与 step 同名定义的顶层 handler (重复定义会编译失败)
	set stepNames to my topLevelHandlerNames(stepBody)
	set readerNames to my topLevelHandlerNames(readerBody)
	repeat with nm in readerNames
		set nmStr to nm as text
		if stepNames contains nmStr then
			set readerBody to my removeTopLevelHandler(readerBody, nmStr)
		end if
	end repeat

	-- step loader 改为指向自身(模块已内联)
	set stepBody to my replaceStr(stepBody, "set typesLib to my loadMod(\"types\", scriptDir)", "set typesLib to me")
	set stepBody to my replaceStr(stepBody, "set readerLib to my loadMod(\"reader\", scriptDir)", "set readerLib to me")
	set stepBody to my replaceStr(stepBody, "set printerLib to my loadMod(\"printer\", scriptDir)", "set printerLib to me")
	set stepBody to my replaceStr(stepBody, "set coreLib to my loadMod(\"core\", scriptDir)", "set coreLib to me")

	-- 删除仅用于外部加载的助手(standalone 不再需要)
	set stepBody to my removeTopLevelHandler(stepBody, "loadMod")
	set stepBody to my removeTopLevelHandler(stepBody, "fileExists")

	-- core 模块去重: 删除 core 中与 step 同名定义的顶层 handler
	set coreNames to my topLevelHandlerNames(coreBody)
	repeat with nm in coreNames
		set nmStr to nm as text
		if stepNames contains nmStr then
			set coreBody to my removeTopLevelHandler(coreBody, nmStr)
		end if
	end repeat

	-- 组装
	set header to "use AppleScript version \"2.8\"" & linefeed & "use scripting additions" & linefeed & "use framework \"Foundation\"" & linefeed & linefeed
	set banner to "-- ===== merged standalone: " & stepName & " (auto-generated by merge.applescript) =====" & linefeed
	set out to header & banner
	set out to out & "-- ----- module: types -----" & linefeed & typesBody & linefeed
	set out to out & "-- ----- module: reader -----" & linefeed & readerBody & linefeed
	set out to out & "-- ----- module: printer -----" & linefeed & printerBody & linefeed
	set out to out & "-- ----- module: core -----" & linefeed & coreBody & linefeed
	set out to out & "-- ----- step body -----" & linefeed & stepBody

	set outPath to baseDir & "/" & stepName & ".standalone.applescript"
	my writeFile(outPath, out)
	return outPath
end run

-- ===================== 文件读写(原生) =====================

on readFile(p)
	set f to (POSIX file p)
	open for access f
	try
		set s to read f as «class utf8»
	on error
		set s to ""
	end try
	close access f
	return s
end readFile

on writeFile(p, txt)
	set f to (POSIX file p)
	open for access f with write permission
	set eof f to 0
	write txt as «class utf8» to f
	close access f
end writeFile

-- ===================== 文本工具 =====================

on splitLines(s)
	set AppleScript's text item delimiters to linefeed
	set parts to text items of s
	set AppleScript's text item delimiters to ""
	return parts
end splitLines

on joinLines(lst)
	set AppleScript's text item delimiters to linefeed
	set res to lst as text
	set AppleScript's text item delimiters to ""
	return res
end joinLines

on replaceStr(s, oldStr, newStr)
	set AppleScript's text item delimiters to oldStr
	set parts to text items of s
	set AppleScript's text item delimiters to newStr
	set res to parts as text
	set AppleScript's text item delimiters to ""
	return res
end replaceStr

-- 去掉开头的连续 use 行
on stripUse(src)
	set linesList to my splitLines(src)
	set idx to 1
	repeat while idx ≤ (count of linesList)
		if item idx of linesList starts with "use " then
			set idx to idx + 1
		else
			exit repeat
		end if
	end repeat
	set kept to {}
	repeat with i from idx to (count of linesList)
		set end of kept to item i of linesList
	end repeat
	return my joinLines(kept)
end stripUse

-- ===================== 顶层 handler 分析 =====================

-- 提取顶层(无缩进) handler 名列表
on topLevelHandlerNames(body)
	set names to {}
	set linesList to my splitLines(body)
	repeat with ln in linesList
		if ln starts with "on " or ln starts with "to " then
			set nm to my firstWordAfter(ln)
			if nm is not "" and nm is not "error" then
				if names does not contain nm then
					set end of names to nm
				end if
			end if
		end if
	end repeat
	return names
end topLevelHandlerNames

-- 取 "on NAME(" / "to NAME(" 中的 NAME
on firstWordAfter(ln)
	-- "on " 与 "to " 都是 3 个字符(含末尾空格), 名字从第 4 个字符开始
	if ln starts with "on " or ln starts with "to " then
		set tail to text 4 thru -1 of ln
	else
		return ""
	end if
	if tail starts with " " then set tail to text 2 thru -1 of tail
	set nm to ""
	repeat with c in characters of tail
		if c is in {" ", "("} then exit repeat
		set nm to nm & c
	end repeat
	return nm
end firstWordAfter

-- 删除名为 name 的顶层 handler 及其整个块
on removeTopLevelHandler(body, name)
	set linesList to my splitLines(body)
	set n to count of linesList
	set startIdx to 0
	repeat with i from 1 to n
		set ln to item i of linesList
		if ln starts with "on " & name & "(" or ln starts with "to " & name & "(" or ln starts with "on " & name & " (" or ln starts with "to " & name & " (" then
			set startIdx to i
			exit repeat
		end if
	end repeat
	if startIdx = 0 then return body

	set depth to 0
	set endIdx to startIdx
	repeat with j from startIdx to n
		set ln2 to item j of linesList
		if my isOpenLine(ln2) then
			set depth to depth + 1
		else if my isCloseLine(ln2) then
			set depth to depth - 1
		end if
		if depth = 0 and j > startIdx then
			set endIdx to j
			exit repeat
		end if
	end repeat

	set kept to {}
	repeat with i from 1 to n
		if i < startIdx or i > endIdx then
			set end of kept to item i of linesList
		end if
	end repeat
	return my joinLines(kept)
end removeTopLevelHandler

-- 块起始行(增加深度)
on isOpenLine(ln)
	if ln starts with "on " then
		if ln contains "(" then return true
		return false
	end if
	if ln starts with "to " then
		if ln contains "(" then return true
		return false
	end if
	if ln starts with "script " then return true
	if ln starts with "if " then return true
	if ln starts with "repeat " then return true
	if ln starts with "tell " then return true
	if ln starts with "try" then return true
	if ln starts with "considering " then return true
	if ln starts with "ignoring " then return true
	if ln starts with "with timeout " then return true
	if ln starts with "with transaction " then return true
	if ln starts with "using terms " then return true
	return false
end isOpenLine

-- 块结束行(减少深度)
on isCloseLine(ln)
	if ln starts with "end" then return true
	return false
end isCloseLine
