#!/bin/bash
MAL_BATCH_IMPL_NO_STDERR=1 MAL_BATCH_IMPL_ECHO_STDIN=1 \
WSLENV=MAL_BATCH_IMPL_NO_STDERR/w:MAL_BATCH_IMPL_ECHO_STDIN/w \
cmd.exe /c "`wslpath -w "$(dirname $0)/${STEP:-stepA_mal}.bat"`" "${@}"